# Setup
title:               Cahier
tagline:             "A Greenhorn's Notebook"
description:         'An open webspace where I can scribble down my random thoughs.'
url:                 'https://biplob1ly.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Biplob Biswas
  url:               https://twitter.com/LonelyLizard6
  email:             biplob1ly@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-167981062-1
