# Setup
title:               Cahier
tagline:             "A Greenhorn's Notebook"
description:         'An open webspace where I can scribble down my random thoughs.'
url:                 'https://biplob1ly.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Biplob Biswas
  twitter:           LonelyLizard6
  email:             biplob1ly@gmail.com
  email_md5:         d4a33459796252062e0a0441faee5cdf
  github:            biplob1ly
  linkedin:          biplob1ly
  goodreads:         biplob1ly
#  google_scholar:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-167981062-1
